[package]
name = "messyenv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.25.0"
clap = {version = "3.2.23", features = ["derive"]}
